CREATE TABLE interventions
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_entrance_date date,
    description       VARCHAR(255),
    quote_date        date                                     NOT NULL,
    start_repair_date date,
    end_repair_date   date,
    registration      VARCHAR(9),
    year              INTEGER,
    no_seq            INTEGER,
    CONSTRAINT pk_interventions PRIMARY KEY (id)
);

ALTER TABLE interventions
    ADD CONSTRAINT FK_INTERVENTIONS_ON_REGISTRATION FOREIGN KEY (registration) REFERENCES bus (registration);

ALTER TABLE interventions
    ADD CONSTRAINT FK_INTERVENTIONS_ON_YENO FOREIGN KEY (year, no_seq) REFERENCES accidents (year, no_seq);