CREATE TABLE involve
(
    third_party_id  INTEGER      NOT NULL,
    injuries_nature VARCHAR(255) NOT NULL,
    material_damage VARCHAR(255) NOT NULL,
    year            INTEGER      NOT NULL,
    no_seq          INTEGER      NOT NULL
);

CREATE TABLE third_parties
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(50)                              NOT NULL,
    last_name   VARCHAR(50)                              NOT NULL,
    birth_date  date                                     NOT NULL,
    address     VARCHAR(100)                             NOT NULL,
    postal_code CHAR                                     NOT NULL,
    city        VARCHAR(50)                              NOT NULL,
    amount_paid DECIMAL(15, 2),
    CONSTRAINT pk_third_parties PRIMARY KEY (id)
);

ALTER TABLE accidents
    ADD date date;

ALTER TABLE accidents
    ADD hour time WITHOUT TIME ZONE;

ALTER TABLE accidents
    ALTER COLUMN date SET NOT NULL;

ALTER TABLE accidents
    ALTER COLUMN hour SET NOT NULL;

ALTER TABLE involve
    ADD CONSTRAINT pk_involve PRIMARY KEY (year, no_seq, third_party_id);

ALTER TABLE involve
    ADD CONSTRAINT FK_INVOLVE_ON_THIRDPARTYID FOREIGN KEY (third_party_id) REFERENCES third_parties (id);

ALTER TABLE involve
    ADD CONSTRAINT FK_INVOLVE_ON_YENO FOREIGN KEY (year, no_seq) REFERENCES accidents (year, no_seq);

ALTER TABLE accidents
    DROP COLUMN accident_date;

ALTER TABLE accidents
    DROP COLUMN accident_hour;